
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jiradb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



openrouter:
  api-key: ${OPENROUTER_API_KEY}
  base-url: ${OPENROUTER_BASE_URL}
  model: ${OPENROUTER_MODEL}


jira:
  url: ${JIRA_URL}
  username: ${JIRA_USERNAME}
  apiToken: ${JIRA_TOKEN}



logging:
  level:
    org.springframework.ai: DEBUG